# Generated by Django 6.0.1 on 2026-01-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P_World_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemMaster',
            new_name='StoreProduct',
        ),
    ]
