# Generated by Django 6.0.1 on 2026-01-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_World_App', '0002_rename_itemmaster_storeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ap_item_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ap_item_image', models.ImageField(blank=True, null=True, upload_to='admin_product_image/')),
                ('ap_pet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ap_available_status', models.BooleanField(default=False)),
                ('ap_item_description', models.TextField(blank=True, null=True)),
                ('ap_created_at', models.DateTimeField(auto_now_add=True)),
                ('ap_updated_at', models.DateTimeField(auto_now=True)),
                ('ap_fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_products', to='P_World_App.itemcategorymaster')),
            ],
        ),
    ]
