# Generated by Django 6.0.1 on 2026-01-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P_World_App', '0003_adminproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreProduct',
            new_name='StoreItem',
        ),
    ]
