# Generated by Django 6.0.1 on 2026-01-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_World_App', '0004_rename_storeproduct_storeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='fk_vendor',
            new_name='fk_store',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='available_status',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='fk_category',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='pet_type',
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='admin_product_image/')),
                ('pet_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('available_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_products', to='P_World_App.itemcategorymaster')),
            ],
        ),
        migrations.AddField(
            model_name='storeitem',
            name='fk_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='P_World_App.masteritem'),
        ),
        migrations.DeleteModel(
            name='AdminProduct',
        ),
    ]
