from django.urls import path, include
from . import views, views_doctor, views_cutomer, views_sitter, views_trainer, views_walker 
from P_World_App.views_manoj import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  
                  path('', views.login_page, name='login_page'),
                  path('dashboard/', views.dashboard, name='dashboard'),
                  # path('add_country/', views.add_country, name='add_country'),
                  path('login_check/', views.login_check, name='login_check'),
                  path('logout/', views.logout, name='logout'),
                  path('customer_list/', views.customer_list, name='customer_list'),
                  path('user_list/<str:user_type>', views.user_list, name='user_list'),
                  path('vendor_appointment_list/<str:vendor_type>', views.vendor_appointment_list, name='vendor_appointment_list'), 
                  path('user_detail/<int:id>/', views.render_to_doctor_detail, name='render_to_doctor_detail'),
                  path('delete_doctor_entry/', views.delete_doctor_entry, name='delete_doctor_entry'),
                  path('delete_customer_entry/', views.delete_customer_entry, name='delete_customer_entry'),
                  path('get_customer_detail/', views.get_customer_detail, name='get_customer_detail'),
                  path('doctor_booking_detail/', views.doctor_booking_detail, name='doctor_booking_detail'),
                  path('filter_appointment_page/', views.filter_appointment_page, name='filter_appointment_page'),

                  ########################################## Doctor Side #####################################################

                  path('Doctor_Signup_api/', views_doctor.Doctor_Signup_api, name='Doctor_Signup_api'),
                  path('create_profile_and_set_availability/', views_doctor.create_profile_and_set_availability,
                       name='create_profile_and_set_availability'),
                  path('login_doctor_api/', views_doctor.login_doctor_api, name='login_doctor_api'),
                  path('Doctor_service_api/', views_doctor.Doctor_service_api, name='Doctor_service_api'),
                  path('get_manage_service_api/', views_doctor.get_manage_service_api, name='get_manage_service_api'),
                  path('Edit_service_manage_api/', views_doctor.Edit_service_manage_api,
                       name='Edit_service_manage_api'),
                  path('Delete_service_manage_api/', views_doctor.Delete_service_manage_api,
                       name='Delete_service_manage_api'),
                  path('upcoming_doctors_appointment_list_api/', views_doctor.upcoming_doctors_appointment_list_api,
                       name='upcoming_doctors_appointment_list_api'),
                  path('edit_doctor_profile_api/', views_doctor.edit_doctor_profile_api,
                       name='edit_doctor_profile_api'),
                  path('add_shift_api/', views_doctor.add_shift_api,
                       name='add_shift_api'),
                  path('edit_shift_api/', views_doctor.edit_shift_api,
                       name='edit_shift_api'),
                  path('delete_shift_api/', views_doctor.delete_shift_api,
                       name='delete_shift_api'),
                  path('get_doctors_availability_list_api/', views_doctor.get_doctors_availability_list_api,
                       name='get_doctors_availability_list_api'),

                  ########################################## Customer Side #####################################################

                  path('get_uesr_details/', views_cutomer.get_uesr_details, name='get_uesr_details'),
                  path('cutomer_signup_api/', views_cutomer.cutomer_signup_api, name='cutomer_signup_api'),
                  
                  path('login_customer_api/', views_cutomer.login_customer_api, name='login_customer_api'),

                  path('add_new_pet_api/', views_cutomer.add_new_pet_api, name='add_new_pet_api'),
                  path('get_pet_list/', views_cutomer.get_pet_list, name='get_pet_list'),
                  path('Edit_pet_api/', views_cutomer.Edit_pet_api, name='Edit_pet_api'),
                  path('get-pet-type/', views_cutomer.get_pet_type, name='get_pet_type'),
                  path('get_item_category/', views_cutomer.get_item_category, name='get_item_category'),
                  path('delete_pet_api/', views_cutomer.delete_pet_api, name='delete_pet_api'),
                  path('add_reminder_pet_api/', views_cutomer.add_reminder_pet_api, name='add_reminder_pet_api'),
                  path('update_reminder_pet_api/', views_cutomer.update_reminder_pet_api,
                       name='update_reminder_pet_api'),
                  path('delete_reminder_pet_api/', views_cutomer.delete_reminder_pet_api,
                       name='delete_reminder_pet_api'),
                  path('get_reminder_pet_list/', views_cutomer.get_reminder_pet_list, name='get_reminder_pet_list'),
                  path('get_all_doctors_list/', views_cutomer.get_all_doctors_list, name='get_all_doctors_list'),
                  path('get_doctors_list_with_service_api/', views_cutomer.get_doctors_list_with_service_api,
                       name='get_doctors_list_with_service_api'),
                  path('edit_userprofile_api/', views_cutomer.edit_userprofile_api, name='edit_userprofile_api'),
                  path('book_doctors_appointment_api/', views_cutomer.book_doctors_appointment_api, name='book_doctors_appointment_api'),
                  path('doctors_appointment_list_api/', views_cutomer.doctors_appointment_list_api, name='doctors_appointment_list_api'),
                  path('like_user_api/', views_cutomer.like_user_api, name='like_user_api'),
                  path('user_rating_api/', views_cutomer.user_rating_api, name='user_rating_api'),
                  path('cancel_doctors_appointment_api/', views_cutomer.cancel_doctors_appointment_api, name='cancel_doctors_appointment_api'),
                  path('update_doctors_appointment_api/', views_cutomer.update_doctors_appointment_api, name='update_doctors_appointment_api'),
                  path('show_doctors_data_api/', views_cutomer.show_doctors_data_api, name='show_doctors_data_api'),
                  path('get_user_profile_api/', views_cutomer.get_user_profile_api, name='get_user_profile_api'),
                  path('get_last_visited_doctors_list/', views_cutomer.get_last_visited_doctors_list, name='get_last_visited_doctors_list'),
                  path('doctors_appointment_detail_api/', views_cutomer.doctors_appointment_detail_api, name='doctors_appointment_detail_api'),
                  path('show_notification_list_api/', views_cutomer.show_notification_list_api, name='show_notification_list_api'),
                  path('del_notification_api/', views_cutomer.del_notification_api, name='del_notification_api'),
                  path('customer_home_api/', views_cutomer.customer_home_api, name='customer_home_api'),
                  path('forgot_password_api/', views_cutomer.forgot_password_api, name='forgot_password_api'),
                  path('change_password_api/', views_cutomer.change_password_api, name='change_password_api'),
                  path('get_delivery_address_api/', views_cutomer.get_delivery_address_api, name='get_delivery_address_api'),
                  ######################### API #########################
                  path("get_bookings/",views_cutomer.get_bookings,name="get_bookings"),
                  path("cancel_booking/",views_cutomer.cancel_booking,name="cancel_booking"),
                  path("cancel_order_api/",views_cutomer.cancel_order_api,name="cancel_order_api"),
                  path("order_history_api/",views_cutomer.order_history_api,name="order_history_api"),
                  path("billing_history_api/",views_cutomer.billing_history_api,name="billing_history_api"),
                  path("get_item_list_api/",views_cutomer.get_item_list_api,name="get_item_list_api"),
                  path("show_cart_items_api/",views_cutomer.show_cart_items_api,name="show_cart_items_api"),
                  path("place_order_api/",views_cutomer.place_order_api,name="place_order_api"),
                  path("get_state_of_country_api/",views_cutomer.get_state_of_country_api,name="get_state_of_country_api"),
                  path("get_province_api/",views_cutomer.get_province_api,name="get_province_api"),
                  path("get_city_api/",views_cutomer.get_city_api,name="get_city_api"),
                  ############################################## Sitter Side #####################################################

                  path('sitter_signup_api/', views_sitter.sitter_signup_api, name='sitter_signup_api'),
                  path('create_sitter_account/', views_sitter.create_sitter_account, name='create_sitter_account'),
                  path('login_sitter_api/', views_sitter.login_sitter_api, name='login_sitter_api'),
                  path('create_sitter_service_api/', views_sitter.create_sitter_service_api,
                       name='create_sitter_service_api'),
                  path('get_sitter_service_api/', views_sitter.get_sitter_service_api, name='get_sitter_service_api'),
                  path('delete_sitter_service_api/', views_sitter.delete_sitter_service_api,
                       name='delete_sitter_service_api'),

                  ################################################ Trainer Side ##################################################

                  path('trainer_signup_api/', views_trainer.trainer_signup_api, name='trainer_signup_api'),
                  path('create_trainer_account/', views_trainer.create_trainer_account, name='create_trainer_account'),
                  path('login_trainer_api/', views_trainer.login_trainer_api, name='login_trainer_api'),
                  path('create_trainer_service_api/', views_trainer.create_trainer_service_api,
                       name='create_trainer_service_api'),
                  path('get_trainer_service_api/', views_trainer.get_trainer_service_api,
                       name='get_trainer_service_api'),
                  path('delete_trainer_service_api/', views_trainer.delete_trainer_service_api,
                       name='delete_trainer_service_api'),

                  ################################################ Walker Side ##################################################

                  path('walker_signup_api/', views_walker.walker_signup_api, name='walker_signup_api'),
                  path('create_walker_account/', views_walker.create_walker_account, name='create_walker_account'),
                  path('login_walker_api/', views_walker.login_walker_api, name='login_walker_api'),
                  path('create_walker_service_api/', views_walker.create_walker_service_api,
                       name='create_walker_service_api'),
                  path('get_walker_service_api/', views_walker.get_walker_service_api, name='get_walker_service_api'),
                  path('delete_walker_service_api/', views_walker.delete_walker_service_api,
                       name='delete_walker_service_api'),
                       
                ############################################## website ########################################################
                path('index/', views.index, name='index'), 
                path('create_account_customer/', views_cutomer.create_account_customer,name='create_account_customer'),
                path('service/<int:v_id>/', views.service_details, name = 'services'),
                path('product_details/<int:id>/',product_details, name = 'product_details'),
                path('cart/', views.cart, name = 'cart'),
                path('checkout/', views.checkout, name = 'checkout'),
                path('items/', items, name = 'items'), 
                path('Search_by_all/', Search_by_all, name = 'Search_by_all'), 
                path('login/', views.customer_login, name = 'login'), 
                path('forgot_password/', views.forgot_password, name = 'forgot_password'), 
                path('customer_logout/', views.customer_logout, name = 'customer_logout'), 
                path('customer_signup/', views.customer_signup, name = 'customer_signup'), 
                path('terms_and_conditions/', views.terms_and_conditions, name = 'terms_and_conditions'), 
                path('add_pets/', views.add_pets, name = 'add_pets'), 
                path('add_new_pet/', views.add_new_pet, name = 'add_new_pet'), 
                path('pets/', views.show_pets, name = 'pets'), 
                path('all/<str:obj>/', views.show_venders, name = 'all'), 
                path('get_state_of_country/', views.get_state_of_country, name = 'get_state_of_country'), 
                path('doctors_appointment/', views.doctors_appointment, name = 'doctors_appointment'), 
                path('show_all_doctors_appointment/', views.show_all_doctors_appointment, name = 'show_all_doctors_appointment'), 
                path('manage_services/', views.manage_services, name = 'manage_services'), 
                path('add_services/', views.add_services, name = 'add_services'), 
                path('doctor_availability/', views.doctor_availability, name = 'doctor_availability'), 
                path('show_doctor_availability/', views.show_doctor_availability, name = 'show_doctor_availability'), 
                path('set_doctor_availability/', views.set_doctor_availability, name = 'set_doctor_availability'), 
                path('delete_doctor_shift/', views.delete_doctor_shift, name = 'delete_doctor_shift'), 
                path('bookings/', views.bookings, name = 'bookings'), 
                path('show_all_bookings/', views.show_all_bookings, name = 'show_all_bookings'), 
                path('filter_vendor_by/', views.filter_vendor_by, name = 'filter_vendor_by'), 
                path('filter_TSW_vendors_by/', views.filter_TSW_vendors_by, name = 'filter_TSW_vendors_by'), 
                path('add_item/', views.add_item, name = 'add_item'), 
                path('add_new_item/', views.add_new_item, name = 'add_new_item'), 
                path('show_vendors_item/', views.show_vendors_item, name = 'show_vendors_item'), 
                path('store_dashboard/', views.store_dashboard, name = 'store_dashboard'), 
                path('delete_store_item/', views.delete_store_item, name = 'delete_store_item'), 
                path('edit_item/<int:id>/', views.edit_item, name = 'edit_item'), 
                path('edit_store_item/', views.edit_store_item, name = 'edit_store_item'), 
                path('filter_vendor_order/', views.filter_vendor_order, name = 'filter_vendor_order'), 
                path('change_order_status/', views.change_order_status, name = 'change_order_status'), 
                path('filter_vendor_order_by_date/', views.filter_vendor_order_by_date, name = 'filter_vendor_order_by_date'), 
                
                ############################################## Store ########################################################
                path("store_orders_list_api/",views_cutomer.store_orders_list_api,name="store_orders_list_api"),
                path("store_past_orders_api/",views_cutomer.store_past_orders_api,name="store_past_orders_api"),
                path("store_add_item_api/",views_cutomer.store_add_item_api,name="store_add_item_api"),
                path("store_update_item_api/",views_cutomer.store_update_item_api,name="store_update_item_api"),
                path("store_delete_item_api/",views_cutomer.store_delete_item_api,name="store_delete_item_api"),
                path("get_all_items_api/",views_cutomer.get_all_items_api,name="get_all_items_api"),
                path("approve_order_api/",views_cutomer.approve_order_api,name="approve_order_api"),
                path("complete_order_api/",views_cutomer.complete_order_api,name="complete_order_api"),
                path("submit_support_ticket_api/",views_cutomer.submit_support_ticket_api,name="submit_support_ticket_api"),

                 
                ################################## manoj#################################
                path('Reminder/',Reminder,name='Reminder'),
                path('Add_Reminder/', Add_Reminder, name = 'Add_Reminder'),  
                path('Edit_Reminder/<int:id>/',Edit_Reminder , name = 'Edit_Reminder'),
                path('Modify_Pets/<int:id>/',Edit_Pet, name='Edit_Pet'),
                path('Save_Edit_Pet/',Save_Edit_Pet,name='Save_Edit_Pet'),
                path('Show_all_services/',Show_all_services,name='Show_all_services'),
                path('Show_appointments/',Show_Appointments , name='Show_Appointments'),
                path('Show_Mybookings/',Show_MyBookings , name='Show_Mybookings'),
                path('Profile/',Edit_Profile_Page , name='Profile'),
                path('Edit_Profile/',Edit_Profile , name= 'Edit_Profile'),
                path('Change_Password/',Change_Password , name='Change_Password'),
                path('User_Password_Change/',User_Change_Password, name='User_Password_Change'),
                path('Search_by_Category_Item/',Search_by_Category_Item,name='Search_by_Category_Item'),
                path('Search_by_PetType_Item/',Search_by_PetType_Item , name='Search_by_PetType_Item'),
                path('Order_History/',OrderHistory , name='Order_History'),
                path('AddtoCart/', Item_AddtoCart , name='AddtoCart'),
                path('Update_Cart/',Update_Cart , name='Update_Cart'),
                path('Remove_Cart_Item/',Remove_Cart_Item , name='Remove_Cart_Item'),
                path('Place_Order/',Place_Order,name='Place_Order'),
                path('Order_Item_Detail/',Order_Item_Detail,name='Order_Item_Detail'),
                path('Get_Province/',views.Get_Province , name='Get_Province'),
                path('temp/',Temp,name='temp'),
                path('temp2/',Temp2,name='temp2'),

                #******************************************** Manoj Api 

                path('Reminder_On_Off/',views_cutomer.Reminder_On_Off,name='Reminder_On_Off'),
                path('Check_User/',views_cutomer.Check_User,name='Check_User'),
              ]